---
title: "drought experiment"
author: "Shane Dewees"
date: "3/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
library(DescTools)
library(gmodels)
library(janitor)
```

use t.test then broom::tidy to get mean, pvalue and confidence intervals. 

```{r, echo=FALSE, message= FALSE, warning=FALSE}
soil_moisture <- read.csv(here("data", "soil_moisture.csv")) %>% 
  mutate(date = mdy(date))

drought_ceol <- soil_moisture %>% 
  filter(date == "2022-03-11", species == "ceol", treatment == "drought") %>% 
  select(id)

drought_rhov <- soil_moisture %>% 
  filter(date == "2022-03-11", species == "rhov", treatment == "drought") %>% 
  select(id)

drought_hear <- soil_moisture %>% 
  filter(date == "2022-03-11", species == "hear", treatment == "drought") %>% 
  select(id)

soil_moisture_3_23 <- read.csv(here("data", "03-23 Soil Moisture Data.csv")) %>% 
  select(Note, Moisture, Timestamp) %>% 
  separate(Note, into = c("species", "id"), sep = " ") %>% 
  rename(soil_moisture = Moisture) %>% 
  rename(date = Timestamp) %>% 
  mutate(species = str_replace(species, "R", "r"),
         species = str_replace(species, "C", "c"),
         species = str_replace(species, "H", "h"),
         date = dmy_hm(date),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought",
                               species == "hear" & id %in% drought_hear$id ~ "drought",
                               TRUE ~ "wet")) %>% 
  separate(date, into = c("date", "time"), sep = " ") %>% 
  select(!time)

soil_moisture_4_10 <- read.csv(here("data", "pulse-data-20220410-121709.csv")) %>% 
  select(Note, Moisture, Timestamp) %>%  
  separate(Note, into = c("species", "id", "treatment"), sep = "-") %>% 
  rename(soil_moisture = Moisture) %>%
  drop_na(id) %>% 
  separate(Timestamp, into = c("date", "time"), sep = " ") %>% 
  mutate(species = str_replace(species, "CEOL", "ceol"),
         date = ymd(date),
         treatment = case_when(treatment == "w" ~ "wet",
                               treatment == "d" ~ "drought",
                               treatment == "d " ~ "drought")) %>% 
    select(!time)

soil_moisture <- soil_moisture %>% 
  mutate(treatment = case_when(species == "ceol" & date == "2022-03-15" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & date == "2022-03-15" & id %in% drought_rhov$id ~ "drought",
                               species == "hear" & date == "2022-03-15" & id %in% drought_hear$id ~ "drought",
                               treatment == "" ~ "wet",
                               TRUE ~ treatment)) %>% 
  rbind(soil_moisture_3_23) %>% 
  rbind(soil_moisture_4_10) %>% 
  mutate(id = as.numeric(id))
```

```{r}
gsw <- read.csv(here("data", "gsw light adap", "2022-03-31", "gsw_light_adap_Shane_2022_03_31T19_26_28_209Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "id", "gsw", "PhiPS2", "Date") %>% 
  rename(stomatal_conductance = gsw) %>% 
  rename(light_adapted_flourescence = PhiPS2) %>% 
  rename(date = Date) %>% 
  mutate(id = as.numeric(id),
         light_adapted_flourescence = as.numeric(light_adapted_flourescence),
         stomatal_conductance = as.numeric(stomatal_conductance),
         date = ymd(date),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"))
gsw_1 <- read.csv(here("data", "gsw light adap", "2022-04-04", "gsw_light_adap_Shane_2022_04_04T19_19_54_010Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "id", "gsw", "PhiPS2", "Date") %>% 
  rename(stomatal_conductance = gsw) %>% 
  rename(light_adapted_flourescence = PhiPS2) %>% 
  rename(date = Date) %>% 
  mutate(id = as.numeric(id),
         light_adapted_flourescence = as.numeric(light_adapted_flourescence),
         stomatal_conductance = as.numeric(stomatal_conductance),
         date = ymd(date),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"))

gsw_2 <- read.csv(here("data", "gsw light adap", "2022-04-06", "gsw_light_adap_Shane_2022_04_07T19_00_28_282Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "id", "gsw", "PhiPS2", "Date") %>% 
  rename(stomatal_conductance = gsw) %>% 
  rename(light_adapted_flourescence = PhiPS2) %>% 
  rename(date = Date) %>% 
  mutate(id = as.numeric(id),
         light_adapted_flourescence = as.numeric(light_adapted_flourescence),
         stomatal_conductance = as.numeric(stomatal_conductance),
         date = ymd(date),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"))

gsw_3 <- read.csv(here("data", "gsw light adap", "2022-04-08", "gsw_light_adap_Shane_2022_04_10T21_36_14_465Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "id", "gsw", "PhiPS2", "Date") %>% 
  rename(stomatal_conductance = gsw) %>% 
  rename(light_adapted_flourescence = PhiPS2) %>% 
  rename(date = Date) %>%
  mutate(id = as.numeric(id),
         species = case_when(species == "ceol" & id %in% c(30, 5, 48, 9, 10, 44) ~ "rhov",
                             TRUE ~ species)) %>% 
  mutate(light_adapted_flourescence = as.numeric(light_adapted_flourescence),
         stomatal_conductance = as.numeric(stomatal_conductance),
         date = ymd(date),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"))
gsw_4 <- read.csv(here("data", "gsw light adap", "2022-04-10", "gsw_light_adap_Shane_2022_04_10T21_36_14_585Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "id", "gsw", "PhiPS2", "Date") %>% 
  rename(stomatal_conductance = gsw) %>% 
  rename(light_adapted_flourescence = PhiPS2) %>% 
  rename(date = Date) %>% 
  mutate(id = as.numeric(id),
         light_adapted_flourescence = as.numeric(light_adapted_flourescence),
         stomatal_conductance = as.numeric(stomatal_conductance),
         date = mdy(date),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"))

gsw_5 <- read.csv(here("data", "gsw light adap", "2022-04-12", "gsw_light_adap_Shane_2022_04_12T21_31_58_675Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "id", "gsw", "PhiPS2", "Date") %>% 
  rename(stomatal_conductance = gsw) %>% 
  rename(light_adapted_flourescence = PhiPS2) %>% 
  rename(date = Date) %>% 
  mutate(id = as.numeric(id),
         light_adapted_flourescence = as.numeric(light_adapted_flourescence),
         stomatal_conductance = as.numeric(stomatal_conductance),
         date = mdy(date),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"))


midday_stomata <- read.csv(here("data", "midday_stomtal_conductance.csv"))%>% 
  rename(stomatal_conductance = stomatal_conducatance) %>% 
  mutate(treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         date = mdy(date)) %>% 
  rbind(gsw) %>% 
  rbind(gsw_1) %>% 
  rbind(gsw_2) %>% 
  rbind(gsw_3) %>% 
  rbind(gsw_4) %>% 
  rbind(gsw_5)

gsw_hour <- read.csv(here("data", "gsw light adap", "2022-04-11", "gsw_light_adap_Shane_2022_04_12T21_31_07_207Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "id", "gsw", "PhiPS2", "Date", "Time") %>% 
  mutate(Time = hms(Time),
         Time = case_when(Time > hms("06:00:00") & Time < hms("07:30:00") ~ hms("08:00:00"),
                          Time > hms("07:30:00") & Time < hms("08:30:00") ~ hms("09:00:00"),
                          Time > hms("08:30:00") & Time < hms("09:30:00") ~ hms("10:00:00"),
                          Time > hms("09:30:00") & Time < hms("010:30:00") ~ hms("11:00:00"),
                          Time > hms("10:30:00") & Time < hms("11:30:00") ~ hms("12:00:00"))) %>% 
  rename(hour = Time) %>% 
  rename(stomatal_conductance = gsw) %>% 
  rename(light_adapted_flourescence = PhiPS2) %>% 
  rename(date = Date) %>% 
  mutate(id = as.numeric(id),
         light_adapted_flourescence = as.numeric(light_adapted_flourescence),
         stomatal_conductance = as.numeric(stomatal_conductance),
         date = mdy(date),
         hour = as.character(hour),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         hour = case_when(hour == "8H 0M 0S" ~ "8:00",
                          hour == "9H 0M 0S" ~ "9:00",
                          hour == "10H 0M 0S" ~ "10:00",
                          hour == "11H 0M 0S" ~ "11:00",
                          hour == "12H 0M 0S" ~ "12:00"))

hourly_stomata <- read.csv(here("data", "hourly_stomatal_conductance.csv"))%>% 
  mutate(treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"), 
         date = mdy(date)) %>% 
  rbind(gsw_hour)


dark_adapted <- read.csv(here("data", "dark adapted", "2022-03-31", "dark_adapted_Shane_Dewees_2022_03_31T19_26_28_179Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "plant id", "Fv/Fm", "Date") %>% 
  rename("id" = "plant id") %>% 
  rename("dark_adapted_flourescence" = "Fv/Fm") %>% 
  rename(date = Date) %>% 
  mutate(date = ymd(date),
         id = str_remove(id, "0"),
         id = as.numeric(id),
         dark_adapted_flourescence = as.numeric(dark_adapted_flourescence),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         water_potential_predawn = NA,
         water_potential_midday = NA)
dark_adapted_1 <- read.csv(here("data", "dark adapted", "2022-04-04", "dark_adapted_Shane_Dewees_2022_04_04T19_19_53_994Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "plant id", "Fv/Fm", "Date") %>% 
  rename("id" = "plant id") %>% 
  rename("dark_adapted_flourescence" = "Fv/Fm") %>% 
  rename(date = Date) %>% 
  mutate(date = mdy(date),
         id = str_remove(id, "0"),
         id = as.numeric(id),
         dark_adapted_flourescence = as.numeric(dark_adapted_flourescence),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         water_potential_predawn = NA,
         water_potential_midday = NA)

dark_adapted_2 <- read.csv(here("data", "dark adapted", "2022-04-06", "dark_adapted_Shane_Dewees_2022_04_07T19_00_28_340Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "plant id", "Fv/Fm", "Date") %>% 
  rename("id" = "plant id") %>% 
  rename("dark_adapted_flourescence" = "Fv/Fm") %>% 
  rename(date = Date) %>% 
  mutate(date = ymd(date),
         id = str_remove(id, "0"),
         id = as.numeric(id),
         dark_adapted_flourescence = as.numeric(dark_adapted_flourescence),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         water_potential_predawn = NA,
         water_potential_midday = NA)

dark_adapted_3 <- read.csv(here("data", "dark adapted", "2022-04-08", "dark_adapted_Shane_Dewees_2022_04_10T21_36_14_544Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "plant id", "Fv/Fm", "Date") %>% 
  rename("id" = "plant id") %>% 
  rename("dark_adapted_flourescence" = "Fv/Fm") %>% 
  rename(date = Date) %>% 
  mutate(date = ymd(date),
         id = str_remove(id, "0"),
         id = as.numeric(id),
         dark_adapted_flourescence = as.numeric(dark_adapted_flourescence),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         water_potential_predawn = NA,
         water_potential_midday = NA)

dark_adapted_4 <- read.csv(here("data", "dark adapted", "2022-04-10", "dark_adapted_Shane_Dewees_2022_04_10T21_36_14_611Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "plant id", "Fv/Fm", "Date") %>% 
  rename("id" = "plant id") %>% 
  rename("dark_adapted_flourescence" = "Fv/Fm") %>% 
  rename(date = Date) %>% 
  mutate(date = ymd(date),
         id = str_remove(id, "0"),
         id = as.numeric(id),
         dark_adapted_flourescence = as.numeric(dark_adapted_flourescence),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         water_potential_predawn = NA,
         water_potential_midday = NA)

dark_adapted_5 <- read.csv(here("data", "dark adapted", "2022-04-11", "dark_adapted_Shane_Dewees_2022_04_12T21_31_07_113Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "plant id", "Fv/Fm", "Date") %>% 
  rename("id" = "plant id") %>% 
  rename("dark_adapted_flourescence" = "Fv/Fm") %>% 
  rename(date = Date) %>% 
  mutate(date = ymd(date),
         id = str_remove(id, "0"),
         id = as.numeric(id),
         dark_adapted_flourescence = as.numeric(dark_adapted_flourescence),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         water_potential_predawn = NA,
         water_potential_midday = NA)

dark_adapted_6 <- read.csv(here("data", "dark adapted", "2022-04-12", "dark_adapted_Shane_Dewees_2022_04_12T21_31_58_622Z_1.csv")) %>% 
  row_to_names(1) %>% 
  filter(!row_number() %in% c(1)) %>% 
  select("species", "plant id", "Fv/Fm", "Date") %>% 
  rename("id" = "plant id") %>% 
  rename("dark_adapted_flourescence" = "Fv/Fm") %>% 
  rename(date = Date) %>% 
  mutate(date = mdy(date),
         id = str_remove(id, "0"),
         id = as.numeric(id),
         dark_adapted_flourescence = as.numeric(dark_adapted_flourescence),
         treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         water_potential_predawn = NA,
         water_potential_midday = NA)

flourescence <- read.csv(here("data","flourescence_water_potentials.csv")) %>% 
  mutate(treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"),
         date = mdy(date)) %>% 
  rbind(dark_adapted) %>% 
  rbind(dark_adapted_1) %>% 
  rbind(dark_adapted_2) %>% 
  rbind(dark_adapted_3) %>% 
  rbind(dark_adapted_4) %>% 
  rbind(dark_adapted_5) %>% 
  rbind(dark_adapted_6) %>% 
  drop_na(date)
```

```{r}
plant_height <- read.csv(here("data", "plant_height.csv"))%>% 
  mutate(treatment = case_when(species == "ceol" & id %in% drought_ceol$id ~ "drought",
                               species == "rhov" & id %in% drought_rhov$id ~ "drought", 
                               species == "hear" & id %in% drought_hear$id ~ "drought", 
                               TRUE ~ "wet"))

leaf_conductance <- read.csv(here("data", "leaf_conductance.csv")) %>%
  mutate(flow_rate_g_s = delta_weight/time_sec) %>% 
  group_by(species, id) %>% 
  summarise(flow_rate_g_s = mean(flow_rate_g_s, na.rm = TRUE),
            mpa = mean(c(leaf_1, leaf_2, leaf_3), na.rm = TRUE),
            leaf_area_cm2 = mean(leaf_area)) %>% 
  mutate(flow_rate_g_s = abs(flow_rate_g_s),
         kleaf = flow_rate_g_s/mpa,
         leaf_area_m2 = leaf_area_cm2/10000,
         kleaf_per_area = kleaf/leaf_area_m2,
         treatment = "wet",
         date = mdy("03/07/2022")) %>% 
  select(species, id, kleaf_per_area, treatment, date)

kleaf <- read.csv(here("data", "kleaf.csv")) %>% 
  mutate(leaf_area_m2 = leaf_area_cm2/10000) %>% 
  rename("kleaf" = "k_g_s_MPa") %>% 
  mutate(kleaf_per_area = kleaf/leaf_area_m2,
         treatment = case_when(numbr %in% drought_ceol$id ~ "drought", 
                               TRUE ~ "wet"),
         date = mdy("03/22/2022")) %>% 
  rename("species" = "sp",
         "id" = "numbr") %>% 
  select(species, id, kleaf_per_area, treatment, date) %>% 
  rbind(leaf_conductance)
```

```{r, echo=FALSE, message= FALSE, warning=FALSE}
soil_moisture_mean <- soil_moisture %>% 
  select(!id) %>% 
  group_by(species, date, treatment) %>% 
  nest(data = soil_moisture) %>% 
  mutate(ci = map(data, ~ MeanCI(.x$soil_moisture))) %>% 
  unnest_wider(ci)


ggplot(soil_moisture_mean, aes(x= date, y = mean, col = treatment)) +
  geom_point()+
  geom_errorbar(aes(ymin = lwr.ci, ymax = upr.ci)) +
  labs(x = "date",
       y = "soil moisture (%)")+
  facet_wrap(~species)

flourescence_mean <- flourescence %>% 
  group_by(species, date, treatment) %>% 
  summarise(mean_flourescence = ci(dark_adapted_flourescence, na.rm = TRUE)[1],
            flourescence_low = ci(dark_adapted_flourescence, na.rm = TRUE)[2],
            flourescence_high = ci(dark_adapted_flourescence, na.rm = TRUE)[3],
            mean_predawn = ci(water_potential_predawn, na.rm = TRUE)[1],
            predawn_low = ci(water_potential_predawn, na.rm = TRUE)[2],
            predawn_high = ci(water_potential_predawn, na.rm = TRUE)[3],
            mean_midday = ci(water_potential_midday, na.rm = TRUE)[1],
            midday_low = ci(water_potential_midday, na.rm = TRUE)[2],
            midday_high = ci(water_potential_midday, na.rm = TRUE)[3])

ggplot(flourescence_mean, aes(date, mean_flourescence, color = treatment))+
  geom_point()+
  geom_errorbar(aes(ymin=flourescence_low, ymax = flourescence_high))+
  labs(x = "date",
       y = "dark adapted flourescence") +
  facet_wrap(~species)

#ggplot(flourescence_mean, aes(species, mean_predawn))+
 # geom_point()+ 
  #geom_errorbar(aes(ymin = mean_predawn-sd_predawn, ymax = mean_predawn+sd_predawn))

#ggplot(flourescence_mean, aes(species, mean_midday))+
 # geom_point()+ 
  #geom_errorbar(aes(ymin = mean_midday-sd_midday, ymax = mean_midday+sd_midday))

#ggplot(flourescence_mean, aes(species, mean_water_potential_change)) +
 # geom_point()

#ggplot(flourescence_mean, aes(mean_midday, mean_predawn))+
  #geom_point(aes(color = species))+
  #geom_abline(slope = 1, intercept = 0)

plant_height_mean <- plant_height %>% 
  group_by(species, treatment) %>% 
  summarise(mean = ci(height)[1],
            lowCI = ci(height)[2],
            highCI = ci(height)[3])

ggplot(plant_height_mean, aes(species, mean, color = treatment))+
  geom_point()+
  geom_errorbar(aes(ymin=lowCI, ymax=highCI)) +
  labs(x = "species",
       y = "plant height (cm)")
```

```{r, echo=FALSE, message= FALSE, warning=FALSE}
hourly_stomata_mean <- hourly_stomata %>% 
  group_by(species, treatment, date, hour) %>% 
  summarise(mean = ci(stomatal_conductance)[1],
            lowci = ci(stomatal_conductance)[2],
            highci = ci(stomatal_conductance)[3]) %>% 
  ungroup() %>% 
  mutate(time_hour = hm(hour))

ggplot(hourly_stomata_mean, aes(x= time_hour@hour, y = mean, col = treatment, shape = as.factor(species)))+
  geom_point(alpha = 0.5)+
  geom_line(aes(x = time_hour@hour, y = mean)) +
  geom_errorbar(aes(ymin=lowci, ymax=highci), size = 0.25) +
  labs(x = "time of day",
       y = "stomatal conductance") +
  facet_wrap(~date)
```

```{r, echo=FALSE, message= FALSE, warning=FALSE}
midday_stomata_mean <- midday_stomata %>%
  group_by(species, date, treatment) %>% 
  summarise(mean = ci(stomatal_conductance)[1],
            lowci = ci(stomatal_conductance)[2],
            highci = ci(stomatal_conductance)[3])

ggplot(midday_stomata_mean, aes(date, mean, color = treatment))+
  geom_point()+
  geom_errorbar(aes(ymin = lowci, ymax = highci)) + 
  labs(x = "date",
       y = "stomatal conductance") +
  facet_wrap(~species)
```

```{r}
kleaf_summary <- kleaf %>% 
  select(!id) %>% 
  group_by(species, date, treatment) %>% 
  nest(data = kleaf_per_area) %>% 
  mutate(ci = map(data, ~MeanCI(.x$kleaf_per_area))) %>% 
  unnest_wider(ci) %>%
  select(!data) %>% 
  as.data.frame() %>% 
  mutate(lwr.ci = case_when(lwr.ci < 0 ~ 0,
                            TRUE~ lwr.ci))

ggplot(kleaf_summary, aes(as.factor(date), mean, col = treatment))+
  geom_point()+
  geom_errorbar(aes(ymin=lwr.ci, ymax=upr.ci)) +
  labs(x = "date",
       y = "kleaf (g/sMpam2)") +
  facet_wrap(~species)

#ggplot(kleaf_summary, aes(treatment, mean_area)) +
#  geom_point() + 
#  geom_errorbar(aes(ymin = low_area, ymax = high_area)) +
#  labs(x = "treatment",
#       y = "leaf area (cm2)")

kleaf_flourescence <- kleaf %>% 
  right_join(flourescence, by = c("species", "id", "date", "treatment")) %>% 
  drop_na(kleaf_per_area) %>% 
  group_by(species, id, date, treatment) %>% 
  summarise(kleaf_per_area = mean(kleaf_per_area, na.rm = TRUE),
            dark_adapted_flourescence = mean(dark_adapted_flourescence, na.rm = TRUE)) %>% 
  filter(date == "2022-03-22")

ggplot(kleaf_flourescence, aes(x = dark_adapted_flourescence, y = kleaf_per_area, col = treatment)) +
  geom_point() +
  facet_wrap(~species)

```



```{r}
stomatal_moisture <- right_join(midday_stomata, soil_moisture, by = c("species", "id", "date", "treatment")) %>% 
  mutate(species = case_when(species == "ceol" ~ "ceanothus",
                             species == "hear" ~ "heteromeles",
                             species == "rhov" ~ "rhus"))

ggplot(stomatal_moisture, aes(x = soil_moisture, y = stomatal_conductance, color = species)) +
  geom_point(alpha = 0.25) +
  geom_smooth(method = "lm", formula = y~x) +
  theme_classic() +
  labs(x = "Soil moisture (%)",
       y = "Stomatal conductance")

ceanothus <- midday_stomata_mean %>% 
  filter(species == "ceol")

rhov <- midday_stomata_mean %>% 
  filter(species == "rhov")

hear <- midday_stomata_mean %>% 
  filter(species == "hear")

ggplot(ceanothus, aes(date, mean, color = treatment))+
  geom_point()+
  geom_errorbar(aes(ymin = lowci, ymax = highci)) + 
  labs(x = "date",
       y = "stomatal conductance") +
  theme_classic()

ggplot(rhov, aes(date, mean, color = treatment))+
  geom_point()+
  geom_errorbar(aes(ymin = lowci, ymax = highci)) + 
  labs(x = "date",
       y = "stomatal conductance") +
  theme_classic()

ggplot(hear, aes(date, mean, color = treatment))+
  geom_point()+
  geom_errorbar(aes(ymin = lowci, ymax = highci)) + 
  labs(x = "date",
       y = "stomatal conductance") +
  theme_classic() +
  labs(x = "Soil moisture (%)",
       y = "Stomatal conductance(mol/m^-2 s^-2 )")

```